### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by derSchorsch** [olivierverdier/pychebfun-old#16]
Unfortunately, when I try to install your package pychebfun on Ubuntu
12.04 from the master-zip-file that I've just downloaded from github,
the following error message shows up:

~/Downloads/pychebfun-master$ python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    import pychebfun
  File ".../pychebfun-master/pychebfun/**init**.py", line 13, in <module>
    from plotting import *
ImportError: No module named plotting

Please give some hints on how to change the installation files in
order to make that package work.

**Comment by olivierverdier** [comment]
You are using python 3. Pychebfun is for Python 2.x.
